### ISSUE TITLE
Empty PSR-7 request object not working anymore

### ISSUE THREAD

**Issue by Lex85** [woohoolabs/yang#16] opened 2019-07-03 12:05 UTC
This part of the README is not working anymore 

`// Instantiate an empty PSR-7 request
$request = new Request("", "")`

since the PRS-7 request got this update

https://github.com/guzzle/psr7/commit/c5aea30ff82a3565e6d3decd18d74257c033daf6#diff-a788147295d6b475ecb28d093c1ba121

The $method parameter cannot be empty anymore since they introduced this check right in the constructor:

`private function assertMethod($method)
    {
        if (!is_string($method) || $method === '') {
            throw new \InvalidArgumentException('Method should be a non empty string.');
        }
    }`

**Comment by kocsismate** [comment] 2019-07-10 17:48
Thanks for the report! The issue is fixed now. :)

**Closed by kocsismate** 2019-07-10 17:48 UTC
